services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend_Service
    container_name: flask_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:mysecretpassword@db:5432/postgres

  frontend:
    build: ./Frontend_Service
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
